package main

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"slices"
	"sort"
	"strings"
)

// caskText describes only declarative files from the verified macOS archives.
// It also audits the pinned packager's generated Ruby without evaluating Ruby.
func caskText(m manifest) ([]byte, error) {
	if err := validateIdentity(m); err != nil {
		return nil, err
	}
	if m.Mode != "candidate" {
		return nil, fmt.Errorf("cask requires stable candidate")
	}
	var out strings.Builder
	fmt.Fprintf(&out, "# This file was generated by GoReleaser. DO NOT EDIT.\ncask \"tusk\" do\n  depends_on :macos\n  version %q\n  on_macos do\n", m.Version)
	var manuals []string
	for i, arch := range []string{"arm64", "amd64"} {
		var records []targetRecord
		for _, r := range m.Targets {
			if r.Target == "darwin/"+arch {
				records = append(records, r)
			}
		}
		if len(records) != 1 {
			return nil, fmt.Errorf("exact macOS architecture required: %s", arch)
		}
		r := records[0]
		if r.Archive != archiveName(m.Version, r.Target) || !regexp.MustCompile(`^[0-9a-f]{64}$`).MatchString(m.Files[r.Archive]) {
			return nil, fmt.Errorf("invalid macOS archive/hash")
		}
		for _, shell := range []string{"bash", "zsh", "fish"} {
			if r.Members["completions/tusk."+shell] == "" {
				return nil, fmt.Errorf("missing completion: %s", shell)
			}
		}
		var names []string
		for name := range r.Members {
			if strings.HasPrefix(name, "man/") {
				if !regexp.MustCompile(`^man/tusk(-[a-z]+)?\.1$`).MatchString(name) {
					return nil, fmt.Errorf("unsafe manual name")
				}
				names = append(names, name)
			}
		}
		sort.Strings(names)
		if !slices.Contains(names, "man/tusk.1") || i > 0 && !slices.Equal(names, manuals) {
			return nil, fmt.Errorf("missing or mismatched manuals")
		}
		manuals = names
		stanza := "on_intel"
		if arch == "arm64" {
			stanza = "on_arm"
		}
		// The packager substitutes Ruby version interpolation in its URLs.
		filename := strings.ReplaceAll(r.Archive, m.Version, "#{version}")
		fmt.Fprintf(&out, "    %s do\n      sha256 %q\n      url \"https://github.com/newbpydev/tusk/releases/download/v#{version}/%s\"\n    end\n", stanza, m.Files[r.Archive], filename)
	}
	out.WriteString("  end\n  name \"tusk\"\n  desc \"Local task management in your terminal\"\n  homepage \"https://github.com/newbpydev/tusk\"\n  livecheck do\n    skip \"Auto-generated on release.\"\n  end\n  binary \"tusk\"\n")
	for _, name := range manuals {
		fmt.Fprintf(&out, "  manpage %q\n", name)
	}
	out.WriteString("  bash_completion \"completions/tusk.bash\"\n  fish_completion \"completions/tusk.fish\"\n  zsh_completion \"completions/tusk.zsh\"\n  # No zap stanza required\nend\n")
	return []byte(out.String()), nil
}
func cask(manifestFile, filename string, write bool) error {
	var m manifest
	if err := readJSON(manifestFile, &m); err != nil {
		return err
	}
	expected, err := caskText(m)
	if err != nil {
		return err
	}
	if write {
		f, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0644)
		if err != nil {
			return err
		}
		_, writeErr := f.Write(expected)
		closeErr := f.Close()
		if writeErr != nil {
			return writeErr
		}
		return closeErr
	}
	st, err := os.Lstat(filename)
	if err != nil {
		return err
	}
	if !st.Mode().IsRegular() {
		return fmt.Errorf("regular cask required")
	}
	got, err := os.ReadFile(filename)
	if err != nil {
		return err
	}
	// Ignore indentation/blank lines only. Preserve statement and comment boundaries.
	lines := func(data []byte) []byte {
		var out strings.Builder
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line != "" {
				out.WriteString(line)
				out.WriteByte('\n')
			}
		}
		return []byte(out.String())
	}
	if !bytes.Equal(lines(got), lines(expected)) {
		return fmt.Errorf("cask differs from verified declarative architecture/hash/file contract")
	}
	return nil
}
