package storage

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
)

// Generated by evaluating each migration prefix with the pinned SQLite runtime.
// These are immutable expected objects, never cached user-database contents.
type schemaCatalogEntry struct {
	SQLHashes []string          `json:"sql_sha256"`
	Objects   map[string]string `json:"objects"`
}

func readSchemaCatalog(data []byte, inventory []migration) (map[string]string, bool) {
	var entries []schemaCatalogEntry
	if len(inventory) == 0 || json.Unmarshal(data, &entries) != nil || len(entries) < len(inventory) {
		return nil, false
	}
	entry := entries[len(inventory)-1]
	if len(entry.SQLHashes) != len(inventory) || len(entry.Objects) == 0 {
		return nil, false
	}
	for i, m := range inventory {
		if entry.SQLHashes[i] != fmt.Sprintf("%x", sha256.Sum256([]byte(m.sql))) {
			return nil, false
		}
	}
	return entry.Objects, true
}
