package main

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/newbpydev/tusk/internal/cli"
	"github.com/spf13/cobra"
)

func readTree(t *testing.T, root string) map[string]string {
	t.Helper()
	files := map[string]string{}
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		files[filepath.ToSlash(rel)] = string(data)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return files
}

func TestDocgen_DeterministicPureTree(t *testing.T) {
	t.Setenv("TUSK_DB_PATH", filepath.Join(t.TempDir(), "never", "tasks.db"))
	t.Setenv("TUSK_TIMEZONE", "bad")
	t.Setenv("TUSK_AUTO_COMPLETE_PARENT", "bad")
	t.Setenv("SOURCE_DATE_EPOCH", "bad-wall-clock")
	first, second := t.TempDir(), t.TempDir()
	var errs bytes.Buffer
	for _, root := range []string{first, second} {
		if code := run([]string{"--output", root}, &errs); code != 0 {
			t.Fatalf("code %d: %s", code, errs.String())
		}
	}
	files := readTree(t, first)
	if !reflect.DeepEqual(files, readTree(t, second)) {
		t.Fatal("checkout/time dependent generation")
	}
	for _, name := range []string{"man/tusk.1", "man/tusk-completion.1", "man/tusk-tui.1", "completions/tusk.bash", "completions/tusk.zsh", "completions/tusk.fish"} {
		if files[name] == "" {
			t.Errorf("missing %s", name)
		}
	}
	for _, data := range files {
		if strings.Contains(data, "Auto generated") {
			t.Error("autogenerated date/footer leak")
		}
	}
	if _, err := os.Stat(os.Getenv("TUSK_DB_PATH")); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("storage created: %v", err)
	}
	if code := run([]string{"--output", first, "--check"}, &errs); code != 0 {
		t.Fatalf("clean output: %s", errs.String())
	}
}

func TestDocgen_ManualSynopsisKeepsArguments(t *testing.T) {
	root := t.TempDir()
	if err := generate(cli.CommandTree(), root); err != nil {
		t.Fatal(err)
	}
	files := readTree(t, root)
	for file, argument := range map[string]string{"man/tusk-add.1": "<title>", "man/tusk-completion.1": "<bash|zsh|fish>", "man/tusk-history.1": "<id>"} {
		if !strings.Contains(files[file], argument) {
			t.Errorf("%s dropped positional syntax %s", file, argument)
		}
	}
}

func TestDocgen_DriftAndOwnedRepair(t *testing.T) {
	root := t.TempDir()
	var errs bytes.Buffer
	if run([]string{"--output", root}, &errs) != 0 {
		t.Fatal(errs.String())
	}
	before := readTree(t, root)
	for _, change := range []string{"changed", "missing", "extra"} {
		path := filepath.Join(root, "man", "tusk.1")
		switch change {
		case "changed":
			if err := os.WriteFile(path, []byte("stale"), 0644); err != nil {
				t.Fatal(err)
			}
		case "missing":
			if err := os.Remove(path); err != nil {
				t.Fatal(err)
			}
		case "extra":
			if err := os.WriteFile(filepath.Join(root, "man", "stale.1"), nil, 0644); err != nil {
				t.Fatal(err)
			}
		}
		if code := run([]string{"--check", "--output", root}, &errs); code != 1 {
			t.Errorf("%s not detected: %d", change, code)
		}
		if err := os.WriteFile(filepath.Join(root, "user-guide.md"), []byte("preserve"), 0644); err != nil {
			t.Fatal(err)
		}
		if code := run([]string{"--output", root}, &errs); code != 0 {
			t.Fatalf("repair: %s", errs.String())
		}
		after := readTree(t, root)
		if after["user-guide.md"] != "preserve" {
			t.Fatal("unowned guide changed")
		}
		delete(after, "user-guide.md")
		if !reflect.DeepEqual(before, after) {
			t.Fatalf("owned outputs were not restored: %s", change)
		}
	}
}

func TestDocgen_InvalidAndFailureRecovery(t *testing.T) {
	var errs bytes.Buffer
	for _, args := range [][]string{{"--wat"}, {"extra"}, {"--output", ""}} {
		if code := run(args, &errs); code != 2 {
			t.Errorf("%v: exit %d", args, code)
		}
	}
	file := filepath.Join(t.TempDir(), "file")
	if err := os.WriteFile(file, []byte("preserve"), 0644); err != nil {
		t.Fatal(err)
	}
	if code := run([]string{"--output", file}, &errs); code != 1 {
		t.Fatalf("non-directory accepted: %d", code)
	}
	if data, _ := os.ReadFile(file); string(data) != "preserve" {
		t.Fatal("original replaced")
	}
	if code := run([]string{"--check", "--output", filepath.Join(t.TempDir(), "absent")}, &errs); code != 1 {
		t.Fatalf("absent output accepted: %d", code)
	}

	root := t.TempDir()
	if run([]string{"--output", root}, &errs) != 0 {
		t.Fatal(errs.String())
	}
	before := readTree(t, root)
	staged := t.TempDir()
	if err := generate(cli.CommandTree(), staged); err != nil {
		t.Fatal(err)
	}
	calls := 0
	rename := func(old, new string) error {
		calls++
		if calls == 4 {
			return errors.New("injected second install failure")
		}
		return os.Rename(old, new)
	}
	if err := publish(staged, root, rename); err == nil {
		t.Fatal("promotion failure ignored")
	}
	if !reflect.DeepEqual(before, readTree(t, root)) {
		t.Fatal("accepted docs lost after second promotion failure")
	}
}

func TestDocgen_GeneratorFailures(t *testing.T) {
	root := cli.CommandTree()
	stage := t.TempDir()
	if err := os.WriteFile(filepath.Join(stage, "man"), nil, 0644); err != nil {
		t.Fatal(err)
	}
	if err := generate(root, stage); err == nil {
		t.Fatal("blocked destination accepted")
	}
	stage = t.TempDir()
	if err := generate(&cobra.Command{Use: "blocked/path", Run: func(*cobra.Command, []string) {}}, stage); err == nil {
		t.Fatal("manual writer failure accepted")
	}
	stage = t.TempDir()
	if err := os.MkdirAll(filepath.Join(stage, "completions", "tusk.bash"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := generate(root, stage); err == nil {
		t.Fatal("completion write failure accepted")
	}
}

func TestDocgen_RejectNestedGeneratedMember(t *testing.T) {
	root := t.TempDir()
	var errs bytes.Buffer
	if run([]string{"--output", root}, &errs) != 0 {
		t.Fatal(errs.String())
	}
	if err := os.Mkdir(filepath.Join(root, "man", "stale-directory"), 0755); err != nil {
		t.Fatal(err)
	}
	if code := run([]string{"--check", "--output", root}, &errs); code != 1 {
		t.Fatalf("extra output directory accepted: %d", code)
	}
}

func TestDocgen_TemporaryAndDestinationFailures(t *testing.T) {
	file := filepath.Join(t.TempDir(), "file")
	if err := os.WriteFile(file, nil, 0644); err != nil {
		t.Fatal(err)
	}
	for _, key := range []string{"TMPDIR", "TMP", "TEMP"} {
		t.Setenv(key, file)
	}
	if err := execute("unused", true, os.Rename); err == nil {
		t.Fatal("broken temporary directory accepted")
	}
}

func TestDocgen_BlockedOwnedDirectory(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "man")
	if err := os.WriteFile(path, []byte("accepted"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := execute(root, false, os.Rename); err == nil {
		t.Fatal("regular file replaced as output directory")
	}
	if data, _ := os.ReadFile(path); string(data) != "accepted" {
		t.Fatal("accepted file changed")
	}
}

func TestDocgen_PromotionFailureRetainsRecovery(t *testing.T) {
	root := t.TempDir()
	if err := execute(root, false, os.Rename); err != nil {
		t.Fatal(err)
	}
	beforeMan, beforeComp := readTree(t, filepath.Join(root, "man")), readTree(t, filepath.Join(root, "completions"))
	calls := 0
	err := execute(root, false, func(old, new string) error {
		calls++
		if calls == 4 {
			return errors.New("second install failed")
		}
		return os.Rename(old, new)
	})
	if err == nil || !strings.Contains(err.Error(), "recovery files retained") {
		t.Fatalf("missing recovery error: %v", err)
	}
	if !reflect.DeepEqual(beforeMan, readTree(t, filepath.Join(root, "man"))) || !reflect.DeepEqual(beforeComp, readTree(t, filepath.Join(root, "completions"))) {
		t.Fatal("previous accepted bytes lost")
	}
	stages, err := filepath.Glob(filepath.Join(root, ".docgen-*"))
	if err != nil || len(stages) != 1 {
		t.Fatalf("recovery files not retained: %v %v", stages, err)
	}
}

func TestDocgen_BackupAndStatFailure(t *testing.T) {
	root, stage := t.TempDir(), t.TempDir()
	if err := execute(root, false, os.Rename); err != nil {
		t.Fatal(err)
	}
	if err := generate(cli.CommandTree(), stage); err != nil {
		t.Fatal(err)
	}
	before := readTree(t, root)
	if err := publish(stage, root, func(string, string) error { return errors.New("backup failed") }); err == nil {
		t.Fatal("backup error ignored")
	}
	if !reflect.DeepEqual(before, readTree(t, root)) {
		t.Fatal("failed backup changed accepted bytes")
	}
	file := filepath.Join(root, "file")
	if err := os.WriteFile(file, nil, 0644); err != nil {
		t.Fatal(err)
	}
	if err := publish(stage, file, os.Rename); err == nil {
		t.Fatal("stat error ignored")
	}
	if err := compare(filepath.Join(root, "absent"), root); err == nil {
		t.Fatal("missing staging directory accepted")
	}
}

func TestDocgen_UnreadableOutputs(t *testing.T) {
	root := t.TempDir()
	file := filepath.Join(root, "unreadable")
	if err := os.WriteFile(file, nil, 0000); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(file, 0644)
	if _, err := os.ReadFile(file); err == nil {
		t.Skip("host permissions do not enforce mode bits")
	}
	if _, err := readGroup(root); err == nil {
		t.Fatal("unreadable member accepted")
	}
}

func TestDocgen_UnwritableOutput(t *testing.T) {
	root := t.TempDir()
	if err := os.Chmod(root, 0500); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(root, 0755)
	if err := os.WriteFile(filepath.Join(root, "probe"), nil, 0600); err == nil {
		t.Skip("host permissions do not enforce mode bits")
	}
	if err := execute(root, false, os.Rename); err == nil {
		t.Fatal("unwritable output accepted")
	}
	if err := os.Chmod(root, 0000); err != nil {
		t.Fatal(err)
	}
	if err := execute(root, false, os.Rename); err == nil {
		t.Fatal("unsearchable output accepted")
	}
}

func TestDocgen_MainExit(t *testing.T) {
	if os.Getenv("TUSK_DOCGEN_MAIN") == "1" {
		os.Args = []string{"docgen", "--wat"}
		main()
		return
	}
	cmd := exec.Command(os.Args[0], "-test.run=^TestDocgen_MainExit$")
	cmd.Env = append(os.Environ(), "TUSK_DOCGEN_MAIN=1")
	err := cmd.Run()
	var exit *exec.ExitError
	if !errors.As(err, &exit) || exit.ExitCode() != 2 {
		t.Fatalf("main usage exit: %v", err)
	}
}
