// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type SchemaMigration struct {
	Version   int64
	Filename  string
	Checksum  string
	AppliedAt string
}

type Task struct {
	ID          string
	Title       string
	Description string
	Status      string
	Priority    int64
	Progress    int64
	ParentID    sql.NullString
	Tags        string
	CreatedAt   string
	UpdatedAt   string
	DueDate     sql.NullString
	CompletedAt sql.NullString
}

type TaskEvent struct {
	Sequence      int64
	TaskID        string
	Kind          string
	ChangedFields string
	OccurredAt    string
}
