// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO task_events(task_id,kind,changed_fields,occurred_at) VALUES(?,?,?,?) RETURNING sequence
`

type AppendEventParams struct {
	TaskID        string
	Kind          string
	ChangedFields string
	OccurredAt    string
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.TaskID,
		arg.Kind,
		arg.ChangedFields,
		arg.OccurredAt,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id,title,description,status,priority,progress,parent_id,tags,created_at,updated_at,due_date,completed_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
`

type CreateTaskParams struct {
	ID          string
	Title       string
	Description string
	Status      string
	Priority    int64
	Progress    int64
	ParentID    sql.NullString
	Tags        string
	CreatedAt   string
	UpdatedAt   string
	DueDate     sql.NullString
	CompletedAt sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Progress,
		arg.ParentID,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DueDate,
		arg.CompletedAt,
	)
	return err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks WHERE id=?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAncestors = `-- name: GetAncestors :many
WITH RECURSIVE ancestors(id) AS (
    SELECT tasks.parent_id FROM tasks WHERE tasks.id=? AND tasks.parent_id IS NOT NULL
    UNION
    SELECT tasks.parent_id FROM tasks JOIN ancestors ON tasks.id=ancestors.id WHERE tasks.parent_id IS NOT NULL
)
SELECT tasks.id, tasks.title, tasks.description, tasks.status, tasks.priority, tasks.progress, tasks.parent_id, tasks.tags, tasks.created_at, tasks.updated_at, tasks.due_date, tasks.completed_at FROM tasks JOIN ancestors ON tasks.id=ancestors.id
`

func (q *Queries) GetAncestors(ctx context.Context, id string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Progress,
			&i.ParentID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueDate,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubtree = `-- name: GetSubtree :many
WITH RECURSIVE subtree(id) AS (
    SELECT tasks.id FROM tasks WHERE tasks.id=?
    UNION
    SELECT tasks.id FROM tasks JOIN subtree ON tasks.parent_id=subtree.id
)
SELECT tasks.id, tasks.title, tasks.description, tasks.status, tasks.priority, tasks.progress, tasks.parent_id, tasks.tags, tasks.created_at, tasks.updated_at, tasks.due_date, tasks.completed_at FROM tasks JOIN subtree ON tasks.id=subtree.id
`

func (q *Queries) GetSubtree(ctx context.Context, id string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getSubtree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Progress,
			&i.ParentID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueDate,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, status, priority, progress, parent_id, tags, created_at, updated_at, due_date, completed_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.ParentID,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueDate,
		&i.CompletedAt,
	)
	return i, err
}

const listCandidates = `-- name: ListCandidates :many
SELECT id, title, description, status, priority, progress, parent_id, tags, created_at, updated_at, due_date, completed_at FROM tasks
WHERE (json_array_length(CAST(?1 AS TEXT))=0 OR status IN (SELECT value FROM json_each(CAST(?1 AS TEXT))))
AND (json_array_length(CAST(?2 AS TEXT))=0 OR priority IN (SELECT value FROM json_each(CAST(?2 AS TEXT))))
AND (CAST(?3 AS INTEGER)=0 OR parent_id IS NULL)
AND (CAST(?4 AS TEXT) IS NULL OR parent_id=CAST(?4 AS TEXT))
AND (CAST(?5 AS TEXT) IS NULL OR due_date < CAST(?5 AS TEXT))
AND (CAST(?6 AS TEXT) IS NULL OR due_date > CAST(?6 AS TEXT))
`

type ListCandidatesParams struct {
	Statuses   string
	Priorities string
	RootOnly   int64
	ParentID   sql.NullString
	DueBefore  sql.NullString
	DueAfter   sql.NullString
}

func (q *Queries) ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listCandidates,
		arg.Statuses,
		arg.Priorities,
		arg.RootOnly,
		arg.ParentID,
		arg.DueBefore,
		arg.DueAfter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Progress,
			&i.ParentID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueDate,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildren = `-- name: ListChildren :many
SELECT id, title, description, status, priority, progress, parent_id, tags, created_at, updated_at, due_date, completed_at FROM tasks WHERE parent_id=?
`

func (q *Queries) ListChildren(ctx context.Context, parentID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Progress,
			&i.ParentID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueDate,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT sequence, task_id, kind, changed_fields, occurred_at FROM task_events WHERE task_id=? ORDER BY sequence
`

func (q *Queries) ListEvents(ctx context.Context, taskID string) ([]TaskEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskEvent{}
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.TaskID,
			&i.Kind,
			&i.ChangedFields,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :execrows
UPDATE tasks SET title=?,description=?,status=?,priority=?,progress=?,parent_id=?,tags=?,updated_at=?,due_date=?,completed_at=? WHERE id=?
`

type UpdateTaskParams struct {
	Title       string
	Description string
	Status      string
	Priority    int64
	Progress    int64
	ParentID    sql.NullString
	Tags        string
	UpdatedAt   string
	DueDate     sql.NullString
	CompletedAt sql.NullString
	ID          string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Progress,
		arg.ParentID,
		arg.Tags,
		arg.UpdatedAt,
		arg.DueDate,
		arg.CompletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
