# This file was generated by GoReleaser. DO NOT EDIT.
cask "tusk" do
  depends_on :macos

  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "3a2032428ebf9e93aee1072a7a2a1fab8e5083a93d716e6b8545d1f111a6e844"
      url "https://github.com/newbpydev/tusk/releases/download/v#{version}/tusk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1aab2f26868f7a2c2fb09bb74758941fda49a61122280947896ca84bfca7ebcd"
      url "https://github.com/newbpydev/tusk/releases/download/v#{version}/tusk_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "tusk"
  desc "Local task management in your terminal"
  homepage "https://github.com/newbpydev/tusk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tusk"
  manpage "man/tusk-add.1"
  manpage "man/tusk-completion.1"
  manpage "man/tusk-delete.1"
  manpage "man/tusk-done.1"
  manpage "man/tusk-edit.1"
  manpage "man/tusk-history.1"
  manpage "man/tusk-list.1"
  manpage "man/tusk-stats.1"
  manpage "man/tusk-tree.1"
  manpage "man/tusk-tui.1"
  manpage "man/tusk-version.1"
  manpage "man/tusk.1"
  bash_completion "completions/tusk.bash"
  fish_completion "completions/tusk.fish"
  zsh_completion "completions/tusk.zsh"

  # No zap stanza required
end
