.nh
.TH "TUSK" "1" "Sep 2026" "Tusk" "Tusk Manual"

.SH NAME
tusk - Tusk \- Zero-friction terminal task management system


.SH SYNOPSIS
\fBtusk [flags]\fP


.SH DESCRIPTION
Tusk - Zero-friction terminal task management system


.SH OPTIONS
\fB--auto-complete-parent\fP[=false]
	Complete parents when all children are done

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for tusk

.PP
\fB--timezone\fP=""
	Date timezone (IANA name)

.PP
\fB-v\fP, \fB--version\fP[=false]
	Print version


.SH SEE ALSO
\fBtusk-add(1)\fP, \fBtusk-completion(1)\fP, \fBtusk-delete(1)\fP, \fBtusk-done(1)\fP, \fBtusk-edit(1)\fP, \fBtusk-history(1)\fP, \fBtusk-list(1)\fP, \fBtusk-stats(1)\fP, \fBtusk-tree(1)\fP, \fBtusk-tui(1)\fP, \fBtusk-version(1)\fP
