.nh
.TH "TUSK-COMPLETION" "1" "Sep 2026" "Tusk" "Tusk Manual"

.SH NAME
tusk-completion - Generate a shell completion script


.SH SYNOPSIS
\fBtusk completion <bash|zsh|fish> [flags]\fP


.SH DESCRIPTION
Generate a shell completion script


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auto-complete-parent\fP[=false]
	Complete parents when all children are done

.PP
\fB--timezone\fP=""
	Date timezone (IANA name)


.SH SEE ALSO
\fBtusk(1)\fP
