.nh
.TH "TUSK-TUI" "1" "Sep 2026" "Tusk" "Tusk Manual"

.SH NAME
tusk-tui - Open the interactive task application


.SH SYNOPSIS
\fBtusk tui [flags]\fP


.SH DESCRIPTION
Open the interactive task application


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for tui


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auto-complete-parent\fP[=false]
	Complete parents when all children are done

.PP
\fB--timezone\fP=""
	Date timezone (IANA name)


.SH SEE ALSO
\fBtusk(1)\fP
