.nh
.TH "TUSK-VERSION" "1" "Sep 2026" "Tusk" "Tusk Manual"

.SH NAME
tusk-version - Print the version of tusk


.SH SYNOPSIS
\fBtusk version [flags]\fP


.SH DESCRIPTION
Print the version of tusk


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auto-complete-parent\fP[=false]
	Complete parents when all children are done

.PP
\fB--timezone\fP=""
	Date timezone (IANA name)


.SH SEE ALSO
\fBtusk(1)\fP
