.nh
.TH "TUSK-DONE" "1" "Sep 2026" "Tusk" "Tusk Manual"

.SH NAME
tusk-done - Complete a task and its descendants


.SH SYNOPSIS
\fBtusk done <id> [flags]\fP


.SH DESCRIPTION
Complete a task and its descendants


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for done

.PP
\fB--json\fP[=false]
	Print complete JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auto-complete-parent\fP[=false]
	Complete parents when all children are done

.PP
\fB--timezone\fP=""
	Date timezone (IANA name)


.SH EXAMPLE
.EX
  tusk done TASK_ID --json
.EE


.SH SEE ALSO
\fBtusk(1)\fP
