// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID           int32            `json:"id"`
	UserID       int32            `json:"user_id"`
	ParentID     pgtype.Int4      `json:"parent_id"`
	Title        string           `json:"title"`
	Description  pgtype.Text      `json:"description"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DueDate      pgtype.Timestamp `json:"due_date"`
	IsCompleted  pgtype.Bool      `json:"is_completed"`
	Status       pgtype.Text      `json:"status"`
	Priority     pgtype.Text      `json:"priority"`
	Tags         []string         `json:"tags"`
	DisplayOrder pgtype.Int4      `json:"display_order"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	LastLogin    pgtype.Timestamp `json:"last_login"`
	IsActive     pgtype.Bool      `json:"is_active"`
}
