// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Task struct {
	ID           int32
	UserID       int32
	ParentID     sql.NullInt32
	Title        string
	Description  sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DueDate      sql.NullTime
	IsCompleted  sql.NullBool
	Status       sql.NullString
	Priority     sql.NullString
	Tags         []string
	DisplayOrder sql.NullInt32
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	LastLogin    sql.NullTime
	IsActive     sql.NullBool
}
